name: sada
description: SADA video calls
publish_to: 'none'
version: 2.0.0+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  jitsi_meet_flutter_sdk: ^1.0.0
  shared_preferences: ^2.2.2

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
